tablefootball/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tablefootball.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^tf/', include('tf.urls', namespace="tf")),
    url(r'^$', include('tf.urls', namespace="tf")),
    url(r'^admin/', include(admin.site.urls)),
)

tf/urls.py
from django.conf.urls import patterns, url

from tf import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<match_id>\d+)/$', views.details, name='match_details'),
    url(r'^matches/$', views.matches, name='matches'),
    url(r'^addmatch/$', views.addmatch, name='addmatch'),
    url(r'^removematch/(?P<match_id>\d+)/$', views.removematch, name='removematch'),
    url(r'^removematchsubmit/(?P<match_id>\d+)/$', views.removematchsubmit, name='removematchsubmit'),
    url(r'^addmatchsubmit/$', views.addmatchsubmit, name='addmatchsubmit'),
    url(r'^player/(?P<player_id>\d+)/$', views.playerpage, name='playerpage'),
)

tf/models.py
from django.db import models

class Player(models.Model):
    player_name = models.CharField("Player Name",max_length=200)
    rank = models.IntegerField("Rank",default=0)
    def __unicode__(self):
        return self.player_name

class Elo(models.Model):   
    player = models.ForeignKey(Player)
    elo_date = models.DateTimeField("Date of Elo") 
    elo = models.IntegerField("Elo",default=1000)
    def __unicode__(self):
        return self.player.__unicode__() + " " + str(self.elo_date)

class Match(models.Model):
    playerRed1 = models.ForeignKey(Player, null=True, related_name=" Red 1")
    playerRed2 = models.ForeignKey(Player, blank=True, null=True, related_name=" Red 2")
    playerBlue1 = models.ForeignKey(Player, null=True, related_name=" Blue 1")
    playerBlue2 = models.ForeignKey(Player, blank=True, null=True, related_name=" Blue 2")
    match_date = models.DateTimeField("Date of Match")
    scoreRed = models.IntegerField("Team Red Score")
    scoreBlue = models.IntegerField("Team Blue Score")
    ordered = models.BooleanField("Ordered",default=False)
    def __unicode__(self):
        return str(self.match_date)

tf/views.py
from datetime import datetime
from tf import elo
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from tf.models import Match, Player, Elo
from django.db.models import Max, Q
import time

def index(request):
    latest_match_list = Match.objects.order_by('-match_date')[:10]

    #Get the list of players ordered by latest elo. Unusually tricky stuff!
    player_list = Player.objects.order_by('player_name').annotate(max_date=Max('elo__elo_date'))
    f = '%Y-%m-%d %H:%M:%S'
    values = tuple([(int(player.id), time.strftime(f,player.max_date.timetuple())) for player in player_list])
    elos = Elo.objects.extra(where=['(player_id, elo_date) IN %s' % (values,)])
    elo_dict = dict([(e.player.id, e) for e in elos])
    player_list = list(player_list)
    for player in player_list:
        player.elo_cache = elo_dict[player.id]
    player_list.sort(key=lambda x: x.elo_cache.elo, reverse=True)

    #Add player's rank, taking into consideration that two players with the same elo should have equal ranks
    c = 1
    prevElo=-1
    curRank = 1
    prevPlayer = player_list[0]
    for player in player_list:
        if prevElo == player.elo_cache.elo:
            player.rank = '%d=' % curRank
            prevPlayer.rank = player.rank
        else:
            player.rank = '%d' % c
            curRank = c
        prevPlayer = player
        prevElo = player.elo_cache.elo
        c = c + 1

    context = { 'latest_match_list': latest_match_list,
                'player_list': player_list }

    matches = Match.objects.all()
    context['redGoals'] = 0
    context['redMatches'] = 0
    context['blueGoals'] = 0
    context['blueMatches'] = 0
    for match in matches:
        context['redGoals'] += match.scoreRed
        context['blueGoals'] += match.scoreBlue
        if match.scoreRed > match.scoreBlue:
            context['redMatches'] += 1
        elif match.scoreBlue > match.scoreRed:
            context['blueMatches'] += 1

    context['redGoalsPercent'] = 100 * context['redGoals'] / (context['redGoals'] + context['blueGoals'])
    context['blueGoalsPercent'] = 100 * context['blueGoals'] / (context['redGoals'] + context['blueGoals'])
    context['redMatchesPercent'] = 100 * context['redMatches'] / (context['redMatches'] + context['blueMatches'])
    context['blueMatchesPercent'] = 100 * context['blueMatches'] / (context['blueMatches'] + context['redMatches'])

    return render(request, 'tf/index.html', context)

def playerpage(request,player_id):
    player = Player.objects.get(id=player_id)
    #stats that I want to begin with:
    #  - Wins/Losses/Elo by match/Elo by day
    #  - I want to show all of this as a progress bar
    elo_list = Elo.objects.filter(player__id=player_id).order_by('elo_date')

    #I want to get at most two elo objects per date - the first and last on every given date
    curDate = None
    c = 0
    elos = list(elo_list)
    lenelos = len(elos)
    for i in range(lenelos-1,-1,-1):
        if (elos[i].elo_date.date() != curDate):
            curDate = elos[i].elo_date.date()
            for j in range(1,c):
                del elos[i+2]
            c = 0
        else:
            c += 1

    context = { 'player' : player, 'elo_list' : elos}

    redPlays = Match.objects.filter(Q(playerRed1=player_id) | Q(playerRed2=player_id))
    context['redWins'] = 0.0
    context['redDraws'] = 0.0
    context['redPlays'] = 0.0

    for play in redPlays:
        context['redPlays']+=1.0
        if play.scoreRed > play.scoreBlue:
            context['redWins']+=1.0
        if play.scoreBlue == play.scoreRed:
            context['redDraws']+=1.0

    bluePlays = Match.objects.filter(Q(playerBlue1=player_id) | Q(playerBlue2=player_id))
    context['blueWins'] = 0.0
    context['blueDraws'] = 0.0
    context['bluePlays'] = 0.0

    for play in bluePlays:
        context['bluePlays']+=1.0
        if play.scoreBlue > play.scoreRed:
            context['blueWins']+=1.0
        if play.scoreBlue == play.scoreRed:
            context['blueDraws']+=1.0

    context['totalWins'] = (context['redWins'] + context['blueWins'])
    context['totalDraws'] = (context['redDraws'] + context['blueDraws'])

    if context['redPlays'] < 0.9:
        context['redWins'] = 0.0
        context['redDraws'] = 0.0
        context['redPlaysPercent'] = 0.0
    else:
        context['redWins'] /= context['redPlays']/100
        context['redDraws'] /= context['redPlays']/100
        context['redPlaysPercent'] = (100 * context['redPlays']) / (context['bluePlays'] + context['redPlays'])
    context['redLosses'] = 100 - context['redWins']

    if context['bluePlays'] < 0.9:
        context['blueWins'] = 0.0
        context['blueDraws'] = 0.0
        context['bluePlaysPercent'] = 0.0
    else:
        context['blueWins'] /= context['bluePlays']/100
        context['blueDraws'] /= context['bluePlays']/100
        context['bluePlaysPercent'] = (100 * context['bluePlays']) / (context['bluePlays'] + context['redPlays'])
    context['blueLosses'] = 100 - context['blueWins']

    context['totalPlays'] = context['redPlays'] + context['bluePlays']
    if context['totalPlays'] < 0.9:
        context['totalWins'] = 0.0
        context['totalDraws'] = 0.0
    else:
        context['totalWins'] /= context['totalPlays']/100
        context['totalDraws'] /= context['totalPlays']/100
    context['totalLosses'] = 100 - context['totalWins']

    return render(request, 'tf/player.html', context)

def matches(request):
    match_list = Match.objects.order_by('-match_date')
    context = { 'match_list' : match_list }
    return render(request, 'tf/matches.html', context)

def addmatch(request):
    player_list = Player.objects.all().order_by('player_name')
    plist = []
    plist.append(dict(id=-1,player_name='-'))
    for p in player_list:
       plist.append(dict(id=p.id,player_name=p.player_name))
    context = { 'datetime' : datetime.now(),
                'player_list_without_null' : player_list,
                'player_list' : plist }
    return render(request, 'tf/addmatch.html', context)

def removematchsubmit(request,match_id):
    Match.objects.get(id=match_id).delete()
    elo.recalculateElos()
    return HttpResponseRedirect(reverse('tf:index'))

def removematch(request,match_id):
    match_obj = Match.objects.get(id=match_id)
    return render(request, 'tf/removematch.html', {'match' : match_obj})

def addmatchsubmit(request):
    #try:
    atts = dict()
    atts['playerRed1'] = Player.objects.get(id=request.POST['playerRed1'])
    if request.POST['playerRed2'] != '-1':
        atts['playerRed2'] = Player.objects.get(id=request.POST['playerRed2'])
    atts['playerBlue1'] = Player.objects.get(id=request.POST['playerBlue1'])
    if request.POST['playerBlue2'] != '-1':
        atts['playerBlue2'] = Player.objects.get(id=request.POST['playerBlue2'])
    atts['match_date'] = request.POST['match_date']
    atts['scoreRed'] = request.POST['scoreRed']
    atts['scoreBlue'] = request.POST['scoreBlue']
    atts['ordered'] = request.POST.has_key('ordered')
    match = Match(**atts)
    match.save()
    elo.recalculateElos()
    return HttpResponseRedirect(reverse('tf:index'))

def details(request, match_id):
    response = "You're looking at the results of match %s."
    return HttpResponse(response % match_id)

# Create your views here.

tf/templates/tf/addmatch.html
{% extends 'tf/base.html' %}      

{% load staticfiles %}

{% block head_block %}
<script type="text/javascript" src="{% static 'tf/js/jquery-1.11.2.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'tf/js/moment.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'tf/bs/js/bootstrap.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'tf/dp/js/bootstrap-datetimepicker.min.js' %}" ></script>
<link href="{% static 'tf/dp/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"/>
{% endblock %}

{% block body_block %} 
<h2>Add Match</h2>
<form role="form" action="{% url 'tf:addmatchsubmit' %}" method="post">
  {% csrf_token %}
  <!--Need to figure out what to put here-->
  <!--Should be date, time, players 1-4, score 1 and 2-->
  <div class="form-group col-xs-12">
      <label for="datetimepicker1">Match Date/Time</label>
      <div class='input-group date' id='datetimepicker1'>
          <input name="match_date" type='text' id="match_date" class="form-control" />
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
      <script type="text/javascript">
          $(function () {
              $('#datetimepicker1').datetimepicker({"date": new Date(),
                 "defaultDate" : false,
                 "useCurrent" : true,
                 "format": "YYYY-MM-DD HH:mm:ss"});
          });
      </script>
  </div>
  <div class="form-group col-xs-12 col-md-6">
    <label for="playerRed1" style="color:red"> Red player 1 (defence):</label>
    <select name="playerRed1" class="form-control" id="playerRed1">
      {% for player in player_list_without_null %}
      <option value="{{ player.id }}">{{ player.player_name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group col-xs-12 col-md-6">
    <label for="playerRed2" style="color:red"> Red player 2 (offence):</label>
    <select name="playerRed2" class="form-control" id="playerRed2">
      {% for player in player_list %}
      <option value="{{ player.id }}">{{ player.player_name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group col-xs-12 col-md-6">
    <label for="playerBlue1" style="color:blue"> Blue player 1 (defence):</label>
    <select name="playerBlue1" class="form-control" id="playerBlue1">
      {% for player in player_list_without_null %}
      <option value="{{ player.id }}">{{ player.player_name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group col-xs-12 col-md-6">
    <label for="playerBlue2" style="color:blue"> Blue player 2 (offence):</label>
    <select name="playerBlue2" class="form-control" id="playerBlue2">
      {% for player in player_list %}
      <option value="{{ player.id }}">{{ player.player_name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group col-xs-6 col-md-6">
    <label for="scoreRed" style="color:red"> Red score</label>
    <input name="scoreRed" class="form-control" type="number" id="scoreRed" min="0" step="1" />
  </div>
  <div class="form-group col-xs-6 col-md-6">
    <label for="scoreBlue" style="color:blue"> Blue score</label>
    <input name="scoreBlue" class="form-control" type="number" id="scoreBlue" min="0" step="1" />
  </div>
  <div class="form-group checkbox col-xs-12 col-md-6 col-md-offset-3">
    <label><input type="checkbox" checked name="ordered" id="ordered"/>Fixed defence/offence</label>
  </div>
  <div class="form-group col-xs-12 col-md-6 col-md-offset-3">
    <input type="submit" class="form-control btn btn-primary" value="Save Match" />
  </div>
  <!--<input type="submit" class="btn btn-primary" value="Save Match and Add Another" />-->
</form>  
{% endblock %}

tf/templates/tf/base.html
{% spaceless %}<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="smcj">

    <title>Table Football</title>

    <link href="{% static 'tf/bs/css/bootstrap-flatly.min.css' %}" rel="stylesheet"/>

    {% block head_block %}{% endblock %}
    
  </head>

  <body role="document">
    <div class="container theme-showcase" role="main">
      <div class="page-header col-xs-12 col-md-8 col-md-offset-2">
        <h1><a href="/tf/">Hawk-Eye Table Football</a></h1>
      </div>
      <div class="col-xs-12 col-md-8 col-md-offset-2"> 
          {% block body_block %}{% endblock %} 
      </div>
    </div>
  </body>
</html>
{% endspaceless %}

tf/templates/tf/index.html
{% extends 'tf/base.html' %}      

{% load staticfiles %}
{% block body_block %}
<h2 style="text-align:center">Current Rankings</h2>
<table class="table table-bordered">
<thead>
  <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>Elo</th>
  </tr>
</thead>
<tbody>
  {% if player_list %}
    {% for player in player_list %}
      <tr>
        <td>{{ player.rank }}</td>
        <td><a href="{% url 'tf:playerpage' player_id=player.id %}">{{ player.player_name }} {% if player.rank == "1" or player.rank == "1=" %} <img src="{% static 'tf/img/crown.png' %}" />{% endif %}</a></td>
        <td>{{player.elo_cache.elo}}</td>
      </tr>
    {% endfor %}
  {% endif %}
</tbody>
</table>
<h2 style="text-align:center">Recent Matches</h2>
<a style = "float:right" href='{% url 'tf:addmatch' %}'>Add Match></a>
{% if latest_match_list %}
<table class="table" style="margin-right:0px;">
  <thead>
  </thead>
  <tbody>
    {% for match in latest_match_list %}
    <tr>
      <td rowspan="2" style="border-right:1px solid #ccc;border-bottom:1px solid #ccc;border-left:1px solid #ccc;border-top:1px solid #ccc;vertical-align:middle;">{{match.match_date|date:"d/m/y H:i:s"}}</td>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;border-top:1px solid #ccc;{% if match.scoreBlue <= match.scoreRed %}font-weight:bold;color:red"> <img src="{% static 'tf/img/crown.png' %}" />{% else %}color:red">{% endif %} {{ match.playerRed1 }} {% if match.playerRed2 %} &amp; {{match.playerRed2}} {% endif %} </td>
      <td style="border-right:1px solid #ccc;border-top:1px solid #ccc;{% if match.scoreRed >= match.scoreBlue %}font-weight:bold;{% endif %}color:red"> {{ match.scoreRed }} </td>
      <td rowspan="2" style="vertical-align:middle;border:1px solid #ccc"><a href='{% url 'tf:removematch' match_id=match.id %}'><span class="glyphicon glyphicon-minus" aria-hidden="true"/></a></td>
    </tr>
    <tr>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;{% if match.scoreBlue >= match.scoreRed %}font-weight:bold;color:blue"> <img src="{% static 'tf/img/crown.png' %}" />{% else %}color:blue">{% endif %} {{ match.playerBlue1 }} {% if match.playerBlue2 %} &amp; {{match.playerBlue2}} {% endif %} </td>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;{% if match.scoreBlue >= match.scoreRed %}font-weight:bold;{% endif %}color:blue"> {{ match.scoreBlue }} </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if latest_match_list.count >= 10 %}
<ul style="text-align:right; float:right; list-style-type: none;">
  <li><a href='{% url 'tf:matches' %}'>View All Matches></a></li>

  <li><a href='{% url 'tf:addmatch' %}'>Add Match></a></li>
</ul>
{% endif %}
{% else %}
    <p>No matches have been played.</p>
{% endif %}
<p style="margin-bottom:2cm;"/>
<h2 style="text-align:center">Table Balance</h2>
<h3>Goals</h3>
</p>
<div class="progress" style="vertical-align:middle;line-height: 30px; height: 40px; font-size:30px;">
    <div class="progress-bar" role="progressbar" style="vertical-align:middle;line-height:30px; font-size:20px;width: {{ redGoalsPercent|floatformat }}%; background-image:none; background-color:#d73c2c">{{redGoals}} ({{ redGoalsPercent|floatformat }}%)</div>
    <div class="progress-bar" role="progressbar" style="vertical-align:middle;line-height:30px;font-size:20px;width: {{ blueGoalsPercent|floatformat }}%; background-image:none; background-color:#2c3e90">{{blueGoals}} ({{ blueGoalsPercent|floatformat }}%)</div>
</div>

<h3>Matches</h3>
</p>
<div class="progress" style="vertical-align:middle;line-height: 30px; height: 40px; font-size:30px;">
    <div class="progress-bar" role="progressbar" style="vertical-align:middle;line-height:30px; font-size:20px;width: {{ redMatchesPercent|floatformat }}%; background-image:none; background-color:#d73c2c">{{redMatches}} ({{ redMatchesPercent|floatformat }}%)</div>
    <div class="progress-bar" role="progressbar" style="vertical-align:middle;line-height:30px;font-size:20px;width: {{ blueMatchesPercent|floatformat }}%; background-image:none; background-color:#2c3e90">{{blueMatches}} ({{ blueMatchesPercent|floatformat }}%)</div>
</div>

{% endblock %}

tf/templates/tf/matches.html
{% extends 'tf/base.html' %}      

{% load staticfiles %}

{% block body_block %}
<h2>Matches</h2>
{% if match_list %}
<a style = "float:right" href='{% url 'tf:addmatch' %}'>Add Match></a>
<table class="table">
  <thead>
    <tr>
      <th style="border:1px solid #ccc">Date/Time</th>
      <th style="border:1px solid #ccc">Players</th>
      <th style="border:1px solid #ccc">Score</th>
    </tr>
  <thead/>
  <tbody> 
  {% for match in match_list %}
    <tr> 
      <td rowspan="2" style="border-right:1px solid #ccc;border-bottom:1px solid #ccc;border-left:1px solid #ccc;border-top:1px solid #ccc;vertical-align:middle;">
              {{match.match_date}}
      </td>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;
        {% if match.scoreBlue <= match.scoreRed %}
          font-weight:bold;color:red"> <img src="{% static 'tf/img/crown.png' %}" />
        {% else %}
          color:red">
        {% endif %} {{ match.playerRed1 }} {% if match.playerRed2 %} &amp; {{match.playerRed2}} {% endif %} </td>
      <td style="border-right:1px solid #ccc;border-top:1px solid #ccc;{% if match.scoreRed >= match.scoreBlue %}font-weight:bold;{% endif %}color:red"> {{ match.scoreRed }} </td>
    </tr>
    <tr>
            <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;{% if match.scoreBlue >= match.scoreRed %}font-weight:bold;color:blue"> <img src="{% static 'tf/img/crown.png' %}" />{% else %}color:blue">{% endif %} {{ match.playerBlue1 }} {% if match.playerBlue2 %} &amp; {{match.playerBlue2}} {% endif %} </td>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;{% if match.scoreBlue >= match.scoreRed %}font-weight:bold;{% endif %}color:blue"> {{ match.scoreBlue }} </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a style = "float:right" href='{% url 'tf:addmatch' %}'>Add Match></a>
{% else %}
    <p>No matches have been played.</p>
{% endif %}
{% endblock %}

tf/templates/tf/removematch.html
{% extends 'tf/base.html' %}      

{% load staticfiles %}

{% block body_block %}
<h2>Remove Match</h2>
<table class="table">
  <thead>
    <tr>
      <th style="border:1px solid #ccc">Date/Time</th>
      <th style="border:1px solid #ccc">Players</th>
      <th style="border:1px solid #ccc">Score</th>
    </tr>
  </thead>
  <tbody> 
    <tr> 
      <td rowspan="2" style="border-right:1px solid #ccc;border-bottom:1px solid #ccc;border-left:1px solid #ccc;border-top:1px solid #ccc;vertical-align:middle;">
              {{match.match_date}}
      </td>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;
        {% if match.scoreBlue <= match.scoreRed %}
          font-weight:bold;color:red"> <img src="{% static 'tf/img/crown.png' %}" />
        {% else %}
          color:red">
        {% endif %} {{ match.playerRed1 }} {% if match.playerRed2 %} &amp; {{match.playerRed2}} {% endif %} </td>
      <td style="border-right:1px solid #ccc;border-top:1px solid #ccc;{% if match.scoreRed >= match.scoreBlue %}font-weight:bold;{% endif %}color:red"> {{ match.scoreRed }} </td>
    </tr>
    <tr>
            <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;{% if match.scoreBlue >= match.scoreRed %}font-weight:bold;color:blue"> <img src="{% static 'tf/img/crown.png' %}" />{% else %}color:blue">{% endif %} {{ match.playerBlue1 }} {% if match.playerBlue2 %} &amp; {{match.playerBlue2}} {% endif %} </td>
      <td style="border-bottom:1px solid #ccc;border-right:1px solid #ccc;{% if match.scoreBlue >= match.scoreRed %}font-weight:bold;{% endif %}color:blue"> {{ match.scoreBlue }} </td>
    </tr>
  </tbody>
</table>
<form action="{% url 'tf:removematchsubmit' match_id=match.id %}"><button type="submit" class="btn btn-lg btn-primary">Delete Entry</button></form>
{% endblock %}